language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "make deploy"
# command to run tests
script: "travis_retry make test-coverage-travis-ci" #nosetests
after_success:
  - "make test-coveralls"
